export const componentTokens = {
  tabBar: {
    horizontalMargin: 12,
    height: 72,
    itemHeight: 44,
    rowPaddingHorizontal: 20,
    rowPaddingVertical: 12,
    activePillPaddingHorizontal: 16,
    activePillGap: 6,
    iconSize: 24,
    bottomInsetMin: 20,
    bottomMargin: 2,
    scenePaddingBottom: 100,
  },
  header: {
    gap: 16,
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderRadius: 25,
    frameBorderBottomWidth: 1,
    titleGroupGap: 12,
    logoWidth: 44.28,
    logoHeight: 28,
    heartButtonSize: 32,
    heartButtonPadding: 8,
    heartIconSize: 16,
  },
  settings: {
    rowHeight: 40,
    iconSize: 32,
    iconLabelGap: 12,
    listHorizontalPadding: 12,
    listTopPadding: 20,
    rowGap: 24,
    versionBottomMargin: 10,
    toggleTrackWidth: 44,
    toggleTrackHeight: 24,
    toggleThumbSize: 20,
    toggleThumbMargin: 2,
  },
  ratingModal: {
    maxWidth: 328,
    cardRadius: 20,
    headerHeight: 101,
    badgeSize: 120,
    badgeBorderWidth: 1.2,
    badgeOverlap: 60,
    starTouchSize: 40,
    starIconSize: 34,
    starIconInset: 3.33,
    starsGap: 8,
    submitButtonHeight: 48,
    submitButtonMaxWidth: 280,
    contentPaddingHorizontal: 16,
    titleMarginTop: 68,
  },
} as const;
