export const componentTokens = {
  tabBar: {
    horizontalMargin: 16,
    height: 72,
    itemHeight: 44,
    rowPaddingHorizontal: 20,
    rowPaddingVertical: 12,
    activePillPaddingHorizontal: 16,
    activePillGap: 6,
    iconSize: 24,
    bottomInsetMin: 20,
    bottomMargin: 2,
    scenePaddingBottom: 100,
  },
  header: {
    gap: 16,
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderRadius: 25,
    frameBorderBottomWidth: 1,
    titleGroupGap: 12,
    logoWidth: 44.28,
    logoHeight: 28,
    heartButtonSize: 32,
    heartButtonPadding: 8,
    heartIconSize: 16,
  },
  homeCategories: {
    sectionTopPadding: 20,
    sectionHorizontalPadding: 16,
    titleToListGap: 12,
    containerWidth: 335,
    containerHeight: 119,
    itemGap: 16,
    imageSize: 90,
    imageRadius: 10,
    labelMaxWidth: 90,
    labelMarginTop: 8,
  },
  homePopularQuote: {
    sectionTopPadding: 24,
    sectionHorizontalPadding: 16,
    titleToCardGap: 12,
    cardGap: 16,
    cardHeight: 360,
    cardRadius: 16,
    cardBackgrounds: [
      '#CC2E49',
      '#C25128',
      '#9D7611',
      '#247D6C',
      '#2271A5',
      '#103E99',
    ],
    cardPaddingHorizontal: 24,
    cardPaddingVertical: 32,
    quoteColor: '#FFFFFF',
    decorColor: '#FFFFFF',
    decorOpacity: 0.1,
    decorLargeSize: 100,
    decorLargeOffset: -32,
    decorSmallSize: 66,
    decorSmallTop: 264,
    /** Overhang past the right edge (Figma: left 283 on 328-wide card). */
    decorSmallRight: -21,
    actionBarHeight: 56,
    /** Soft transparent overlay — no BlurView (xlight caused white glow on icons) */
    actionBarBackground: 'rgba(255, 255, 255, 0.1)',
    actionBarTopBorder: 'rgba(255, 255, 255, 1)',
    actionItemWidth: 42,
    actionItemHeight: 24,
    actionIconSize: 24,
    actionIconGap: 4,
    actionCountColor: '#FFFFFF',
    /** Figma: 30×30 at top 16 / left 282 on 328-wide card → right 16 */
    editButtonSize: 30,
    editButtonTop: 16,
    editButtonRight: 16,
  },
  settings: {
    rowHeight: 40,
    iconSize: 32,
    iconLabelGap: 12,
    listHorizontalPadding: 12,
    listTopPadding: 20,
    rowGap: 24,
    versionBottomMargin: 35,
    toggleTrackWidth: 44,
    toggleTrackHeight: 24,
    toggleThumbSize: 20,
    toggleThumbMargin: 2,
  },
  ratingModal: {
    maxWidth: 328,
    cardRadius: 20,
    headerHeight: 101,
    badgeSize: 120,
    badgeBorderWidth: 1.2,
    badgeOverlap: 60,
    starTouchSize: 40,
    starIconSize: 34,
    starIconInset: 3.33,
    starsGap: 8,
    submitButtonHeight: 48,
    submitButtonMaxWidth: 280,
    contentPaddingHorizontal: 16,
    titleMarginTop: 68,
  },
  searchBar: {
    height: 45,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    iconSize: 20,
    /** Gap between search icon and placeholder text */
    iconGap: 16,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 20,
    /**
     * Anek Gujarati sits optically high in TextInput —
     * nudge text down so top/bottom gaps look equal.
     */
    textOpticalOffset: 3,
  },
  categoryGrid: {
    /** Screen content width on 360 design = 328 with 16 side insets */
    horizontalPadding: 16,
    gap: 16,
    sectionTopPadding: 16,
    paddingBottom: 2,
    cardRadius: 10,
    /** Width:height ≈ 4:3 — fills column width, height follows */
    cardAspectRatio: 4 / 3,
    overlayHeight: 33,
    overlayPaddingVertical: 6,
    overlayGap: 10,
    /** Softer than tab bar — subtle frosted strip */
    overlayBlurAmountIos: 8,
    overlayBlurAmountAndroid: 10,
    overlayTint: 'rgba(0, 0, 0, 0.08)',
    /** Soft separator above the label bar */
    overlayTopBorder: 'rgba(255, 255, 255, 0.2)',
    overlayTopBorderWidth: 1,
    labelColor: '#FFFFFF',
    fallbackBackground: '#C8C8C8',
  },
  subcategoryHeader: {
    /** Figma frame 82 includes ~40 status + 42 bar */
    barHeight: 50,
    paddingVertical: 8,
    paddingHorizontal: 16,
    gap: 16,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    background: '#FAFAFA',
    backIconSize: 24,
  },
} as const;
